version: "3.9"
services:
  postgresdb:
    container_name: postgresql
    image: postgresql:latest
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb
    restart: always

  application:
    container_name: jwt_app
    build: .
    environment:
      POSTGRESQL_ADDRESS: postgresdb # 위에 생성할 postgres db
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: root
    ports:
    - "8080:8080"
    restart: always
    depends_on:
      - postgresdb