version: "3.9"
services:
  postgresdb:
    container_name: postgresdb
    image: postgres:latest
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=testdb
      - POSTGRES_USER=root
    restart: always

  application:
    container_name: jwt_app
    build: .
    environment:
      - POSTGRES_HOST=postgresdb
      - POSTGRESQL_ADDRESS=postgresql
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root
    ports:
    - "8080:8080"
    restart: always
    depends_on:
      - postgresdb