version: "3.9"
services:
  postgresdb:
    container_name: postgresdb
    image: postgres:latest
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always

  application:
    container_name: jwt_app
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_DATASOURCE_DRIBERCLASSNAME=org.postgresql.Driver
    ports:
    - "8080:8080"
    restart: always
    depends_on:
      - postgresdb